"""
demo/_base.py
Shared helpers for all demo scripts: artifact writing, timing simulation,
decision log writing, comparison files, model.py, runs/ population.
"""
from __future__ import annotations
import csv
import json
import time
import pickle
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parents[1]
RUNS_LOG = ROOT / "runs" / "decision_logs" / "decision_dataset.csv"


# ── Config loader ─────────────────────────────────────────────────────────────

def load_config(path: Path | None = None) -> dict:
    """Load config.yaml; return a flat-ish dict of demo-relevant values."""
    try:
        import yaml
    except ImportError:
        return {}
    cfg_path = path or ROOT / "config.yaml"
    if not cfg_path.exists():
        return {}
    with open(cfg_path) as f:
        raw = yaml.safe_load(f) or {}
    return {
        "mode":             raw.get("mode", "beginner"),
        "max_iterations":   raw.get("execution", {}).get("max_iterations", 5),
        "timeout_per_run":  raw.get("execution", {}).get("timeout_per_run", 300),
        "random_seed":      raw.get("execution", {}).get("random_seed", 42),
        "test_size":        raw.get("split", {}).get("test_size", 0.2),
        "split_method":     raw.get("split", {}).get("method", "stratified"),
        "enable_mlflow":    raw.get("logging", {}).get("enable_mlflow", False),
        "enable_tensorboard": raw.get("logging", {}).get("enable_tensorboard", False),
        "log_level":        raw.get("logging", {}).get("log_level", "info"),
    }


# ── Timing ────────────────────────────────────────────────────────────────────

def _sleep(s: float) -> float:
    time.sleep(s)
    return s


# ── Artifact helpers ──────────────────────────────────────────────────────────

def write_artifacts(out_dir: Path, run_id: str, model_obj, metrics: dict, config: dict) -> None:
    art = out_dir / "artifacts" / run_id
    art.mkdir(parents=True, exist_ok=True)
    (art / "metrics.json").write_text(json.dumps(metrics, indent=2))
    (art / "config.json").write_text(json.dumps(config, indent=2))
    with open(art / "model.pkl", "wb") as f:
        pickle.dump(model_obj, f)


def write_model_py(out_dir: Path, run_id: str, model_name: str, best_metric: float, hyperparams: dict) -> Path:
    p = out_dir / "model.py"
    p.write_text(f'''"""
model.py — Auto-generated by StratML
Run ID  : {run_id}
Model   : {model_name}
Metric  : {best_metric}
"""

import joblib
import numpy as np
from pathlib import Path

# ── Load model ────────────────────────────────────────────────────────────────
MODEL_PATH = Path(r"outputs/{run_id}/artifacts/{run_id}/model.pkl")
model = joblib.load(MODEL_PATH)

# ── Hyperparameters used ──────────────────────────────────────────────────────
hyperparameters = {hyperparams!r}

# ── Predict ───────────────────────────────────────────────────────────────────
def predict(X):
    return model.predict(np.array(X))

def predict_proba(X):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(np.array(X))
    raise NotImplementedError(f"{{type(model).__name__}} does not support predict_proba")

if __name__ == "__main__":
    print(f"Model : {{type(model).__name__}}")
    print(f"Params: {{model.get_params()}}")
    print("Ready. Call predict(X) or predict_proba(X).")
''', encoding="utf-8")
    return p


def write_decision_log(out_dir: Path, run_id: str, iteration: int, record: dict) -> None:
    log_dir = out_dir / "decision_logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    fname = log_dir / f"{run_id}_{iteration:04d}.json"
    fname.write_text(json.dumps(record, indent=2))


def write_counterfactual(out_dir: Path, run_id: str, entries: list[dict]) -> None:
    log_dir = out_dir / "decision_logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps({**e, "experiment_id": run_id}) for e in entries]
    (log_dir / "counterfactual_log.jsonl").write_text("\n".join(lines) + "\n")


def write_comparison(out_dir: Path, rows: list[dict]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    keys = list(rows[0].keys())
    with open(out_dir / "comparison.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)
    (out_dir / "comparison.json").write_text(json.dumps(rows, indent=2))


def append_runs_log(run_id: str, rows: list[dict]) -> None:
    RUNS_LOG.parent.mkdir(parents=True, exist_ok=True)
    write_header = not RUNS_LOG.exists()
    with open(RUNS_LOG, "a", newline="") as f:
        if rows:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            if write_header:
                w.writeheader()
            w.writerows(rows)


def write_report_pdf(out_dir: Path, run_id: str, dataset_name: str, rows: list[dict]) -> Path:
    """Generate a real PDF report using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors

        pdf_path = out_dir / "report.pdf"
        doc = SimpleDocTemplate(str(pdf_path), pagesize=A4,
                                leftMargin=2*cm, rightMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        story = []

        story.append(Paragraph(f"StratML Run Report", styles["Title"]))
        story.append(Paragraph(f"Run ID: {run_id}", styles["Normal"]))
        story.append(Paragraph(f"Dataset: {dataset_name}", styles["Normal"]))
        story.append(Spacer(1, 0.5*cm))

        # Table
        headers = ["Iter", "Model", "Action", "Trigger", "Primary", "F1", "Gap", "Runtime"]
        table_data = [headers]
        for r in rows:
            table_data.append([
                str(r.get("iteration", "")),
                str(r.get("model", ""))[:24],
                str(r.get("action", "")),
                str(r.get("trigger", "")),
                f"{r.get('primary_metric', 0):.4f}" if r.get("primary_metric") else "-",
                f"{r.get('f1_score', 0):.4f}" if r.get("f1_score") else "-",
                f"{r.get('train_val_gap', 0):.4f}",
                f"{r.get('runtime', 0):.2f}s",
            ])
        t = Table(table_data, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f2f2")]),
        ]))
        story.append(t)
        doc.build(story)
        return pdf_path
    except Exception:
        # Fallback: empty file
        pdf_path = out_dir / "report.pdf"
        pdf_path.write_bytes(b"")
        return pdf_path


# ── State snapshot builder ────────────────────────────────────────────────────

def make_state(run_id, iteration, model_name, model_type, metrics, signals,
               dataset, trajectory, resources, candidates, selected,
               max_iterations, previous_action=None, time_budget=300.0):
    ts = datetime.now(timezone.utc).isoformat()
    primary = metrics.get("accuracy") or metrics.get("r2") or 0.0
    return {
        "experiment_id": run_id,
        "iteration": iteration,
        "timestamp": ts,
        "state_snapshot": {
            "meta": {"experiment_id": run_id, "iteration": iteration, "timestamp": ts},
            "objective": {"primary_metric": "accuracy" if metrics.get("accuracy") is not None else "r2",
                          "optimization_goal": "maximize"},
            "metrics": {
                "primary": primary,
                "secondary": {
                    "accuracy": metrics.get("accuracy"),
                    "precision": metrics.get("precision"),
                    "recall": metrics.get("recall"),
                    "f1_score": metrics.get("f1_score"),
                    "mse": metrics.get("mse"),
                    "rmse": metrics.get("rmse"),
                    "r2": metrics.get("r2"),
                },
                "train_val_gap": metrics.get("gap", 0.0),
            },
            "trajectory": trajectory,
            "dataset": dataset,
            "model": {
                "model_name": model_name,
                "model_type": model_type,
                "hyperparameters": {},
                "complexity_hint": "low",
                "runtime": resources.get("runtime", 0.0),
                "convergence_epoch": iteration,
                "early_stopped": None,
            },
            "generalization": {
                "train_loss": metrics.get("train_loss", 0.0),
                "validation_loss": metrics.get("validation_loss", 0.0),
                "gap": metrics.get("gap", 0.0),
            },
            "resources": {
                "runtime": resources.get("runtime", 0.0),
                "gpu_used": False,
                "cpu_time": resources.get("runtime", 0.0),
                "remaining_budget": resources.get("remaining_budget", 0.0),
                "budget_exhausted": resources.get("budget_exhausted", False),
            },
            "search": {
                "models_tried": resources.get("models_tried", []),
                "unique_models_count": len(resources.get("models_tried", [])),
                "repeated_configs": 0,
            },
            "signals": signals,
            "uncertainty": {"prediction_variance": None, "confidence": None},
            "action_context": {
                "previous_action": previous_action,
                "previous_action_success": None,
                "action_effect_magnitude": None,
            },
            "constraints": {
                "allowed_models": [],
                "max_iterations": max_iterations,
                "time_budget": time_budget,
            },
        },
        "candidate_actions": candidates,
        "selected_action": selected,
    }


def _no_signals():
    keys = ["underfitting","overfitting","well_fitted","converged","stagnating",
            "diverging","unstable_training","high_variance","too_slow",
            "plateau_detected","diminishing_returns"]
    return {k: "none" for k in keys} | {k+"_confidence": 0.0 for k in keys}


def _signals(**overrides):
    s = _no_signals()
    s.update(overrides)
    return s


def _selected(run_id, iteration, action_type, params, trigger, confidence,
              perf, eff, stab, evidence=None, preprocessing=None):
    return {
        "experiment_id": run_id,
        "iteration": iteration,
        "action_type": action_type,
        "parameters": params,
        "preprocessing": preprocessing or {
            "missing_value_strategy": "mean",
            "scaling": "standard",
            "encoding": "onehot",
            "imbalance_strategy": "none",
            "feature_selection": "none",
        },
        "bootstrap_context": None,
        "expected_gain": 0.05,
        "expected_cost": 0.5,
        "confidence": confidence,
        "agent_scores": {"performance": perf, "efficiency": eff, "stability": stab},
        "reason": {
            "trigger": trigger,
            "evidence": evidence or {},
            "source": "rule",
        },
    }
